version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Get current directory
          command: pwd

      - run:
          name: Get python
          command: which python3